name: ErrLog
main: io.github.skepter.errlog.Main
version: 1.1-BETA
description: Allows you to view the console
author: Skepter
website: http://skepter.github.io/

commands:
   errlog:
     description: Allows you to view errors.
     permission: errlog.use
   errview:
     description: Views an error log
     permission: errlog.use
   errlogs:
     description: Allows you to view previous errors.
     permission: errlog.use